### PR TITLE
Fix for publishing Heading2 and DualAntennaHeading information

### LINKED ISSUE #53: Heading2 not being published
I have the latest version of novatel_gps_driver compiled from source. I am running it on ROS Kinetic on Ubuntu 16.04. I have the Novatel PwrPak7D with Dual Antennas. 

When I run the node, no information is being published to the heading2 topic even though the heading2 topic is listed. I have edited the launch file to publish the heading2 information. When I look at the Novatel Connect software, I can see the Align status and get the heading information. 

Also the other information like the UTM and bestpos topics are being published. But there aren't any messages being published to the heading2 or the dual_antenna topics.

### PR DESCRIPTION
**Pull request by sharvil-patankar**
Fixes #53

### CODE REVIEW

**Comment by pjreed** [comment]
@msmcconnell: Since you originally added the Heading2/DualAntennaHeading messages, could you check and see if these changes work for you?

**Comment by sharvil-patankar** [comment]
Can handle both binary and ASCII logs now

**Comment by msmcconnell** [comment]
@pjreed I'm happy to test it but it will be a few days before I can get around to it.

**Comment by msmcconnell** [comment]
@pjreed I have tested these changes and confirmed they are working. 

@sharvil-patankar It looks like there is a merge conflict that needs to be fixed before this can be merged.

**Comment by sharvil-patankar** [comment]
Resolved merge conflicts

**Pull request merged**
