### PR TITLE
Feature/add dual antenna heading msg

### PR DESCRIPTION
**Pull request by msmcconnell**
The NovATel OEM7 specification includes a DUALANTENNAHEADING message which reports the heading of the vehicle relative to north at a faster rate than HEADING2. This PR adds support for this message type by adding a NovatelDualAntennaHeading.msg file and the associated parser (dual_antenna_heading.h/.cpp). The messages are published to the /dual_antenna_heading topic. This was tested on a NovATel PwrPak7.

The DUALANTENNAHEADING message spec
https://docs.novatel.com/OEM7/Content/Logs/DUALANTENNAHEADING.htm

### CODE REVIEW

**Comment by msmcconnell** [comment]
@pjreed 
The travis build for this failed on melodic install
```
Function 'rosdep_install' returned with code '1' after 2 min 27 sec
The command "source .ci_config/travis.sh" exited with 1.
```
I'm developing on Kinetic. Do you have any thoughts on what might have caused this?

**Comment by pjreed** [comment]
It looks like that was just a transient network failure, I pushed the button to retry and it worked.

**Comment by msmcconnell** [comment]
Thanks!

**Comment by msmcconnell** [comment]
@pjreed Any movement on this?

**Comment by pjreed** [comment]
Sorry for the delay on that, but this looks good.  Thanks!

**Pull request merged**
