### PR TITLE
Fix humble build errors tf2 and rclcpp_components

### LINKED ISSUE #115: humble build errors tf2 and rclcpp_components
When building for humble these build errors currently appear:

```sh
ros-humble-novatel-gps-driver-4.1.0/src/novatel_gps.cpp: In member function ‘void novatel_gps_driver::NovatelGps::GenerateImuMessages()’:
ros-humble-novatel-gps-driver-4.1.0/src/novatel_gps.cpp:947:36: error: no matching function for call to ‘toMsg(tf2::Quaternion&)’
  947 |       imu->orientation = tf2::toMsg(q);
```

```sh
novatel_gps_driver/novatel_gps_driver/src/nodes/novatel_gps_node.cpp:1146:10: fatal error: rclcpp_components/register_node_macro.hpp: No such file or directory
[build]  1146 | #include <rclcpp_components/register_node_macro.hpp>
```

I have fixed them and will open a PR.

### PR DESCRIPTION
**Pull request by devrite**
FIxes #115.

### CODE REVIEW

**Comment by devrite** [comment]
Uses ` __has_include` to select non-deprecated header if available. This feature has been added with C++17 if I am not mistaken but is available with g++ anyway.

Some alternatives would be:
* Check the version of tf2_geometry_msgs and set a peproc flag
* Separate branches

**Comment by danthony06** [comment]
I think __has_include is a C++17 feature, and we're still releasing this for ROS2 Foxy, which targets C++14. I'd prefer a different method of doing the conditional include so that we don't have to maintain separate forks for the releases.

**Comment by devrite** [comment]
> I think __has_include is a C++17 feature, and we're still releasing this for ROS2 Foxy, which targets C++14. I'd prefer a different method of doing the conditional include so that we don't have to maintain separate forks for the releases.

Tested with foxy. Gcc supports it anyway. So unless we encounter a compile that does not the branch currently compile just fine with foxy.

**Comment by devrite** [comment]
And it even works with clang (10) in foxy.

**Comment by devrite** [comment]
@danthony06 Switched to cmake based version check. As far as I can tell the new style header is available from 0.18.0 onwards.

**Review by danthony06 — APPROVED** [review]

**Comment by danthony06** [comment]
Looks good, thanks!

**Pull request merged**
