### PR TITLE
Add support for BESTXYZ topic

### PR DESCRIPTION
**Pull request by msmcconnell**
The NovATel OEM7 specification includes a BESTXYZ message which reports the location of the vehicle in an ECEF frame. This PR adds support for this message type by adding a NovatelXYZ.msg file and the associated parser (bestxyz.h/.cpp). The messages are published to the /bestxyz topic. This was tested on a NovATel PwrPak7. 

The BESTXYZ message spec
https://docs.novatel.com/OEM7/Content/Logs/BESTXYZ.htm?tocpath=Logs%7CView%20Logs%7CGNSS%20Logs%7C_____18

### CODE REVIEW

**Comment by msmcconnell** [comment]
I would like to add unit tests to this, but first I want to know if there are any special requirements for the .pcap files used in the existing test cases.

**Comment by msmcconnell** [comment]
Added unit test to parser_tests.cpp

**Comment by msmcconnell** [comment]
@pjreed The travis build passed, but it looks like github hasn't updated the check indicator. Any idea why?

**Comment by pjreed** [comment]
No special requirements on the pcap files, but thanks for adding that.  I think that's also just a glitch with GitHub or Travis, it seems like sometimes the status indicator doesn't update after a build is done...

**Pull request merged**
